export const dbUrl = 'mongodb://127.0.0.1:27017';
export const ramdaCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/ramda/0.26.1/ramda.min.js';
export const reactCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/react/16.8.6/umd/react.production.min.js';
export const reactDomCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.production.min.js';
export const recomposeCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/recompose/0.26.0/Recompose.min.js';
export const reduxCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/redux/4.0.0/redux.min.js';
export const reactReduxCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/react-redux/5.0.7/react-redux.min.js';
export const reduxThunkCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/redux-thunk/2.2.0/redux-thunk.min.js';
export const reselectCdnUrl = 'https://cdnjs.cloudflare.com/ajax/libs/reselect/4.0.0/reselect.min.js';
export const DOMAIN = 'mytracks.store';
export const metrikaCounterId = 54472858;
export const demoAthleteId = 8134866;
export const YMAPS_JSONP_CALLBACK = '__YMAPS_JSONP_CALLBACK__';
export const STRAVA_CLIENT_ID = '32976';
export {default as buildVersion} from '../../buildVersion';
export const INSTANCE_ID_COOKIE_NAME = 'instance_id';
export const SESSION_ID_COOKIE_NAME = 'session_id';
